project:
  type: website

website:
  title: RSE South West
  description: "A group of Research Software Engineers in the South West of England"
  navbar:
   left:
    - text: "Home"
      href: index.qmd
    - text: "Meetings"
      href: meetings/index.qmd
    - text: "Resources"
      href: resources/index.qmd
    - text: "Members"
      href: members/index.qmd
  page-footer:
    center: Â© [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)
  search: false

format:
  html:
    theme: assets/styles.scss
    page-layout: full
